"""
Create a simple test page to test the pronunciation component directly.
This version specifically tests the fix for IPA character rendering.
"""

import os

def create_test_page():
    """Create a simple HTML page that tests the pronunciation component."""
    
    # Get the path to the pronunciation-forms.js file
    app_dir = os.path.join(os.getcwd(), 'app')
    static_dir = os.path.join(app_dir, 'static')
    js_file = os.path.join(static_dir, 'js', 'pronunciation-forms.js')
    
    # Create a simple HTML file that includes the component
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Pronunciation Component Test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        body {{ padding: 20px; }}
        .container {{ max-width: 800px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Pronunciation Component Test</h1>
        <p class="lead">This test checks if IPA characters are correctly displayed.</p>
        
        <div class="card mt-4">
            <div class="card-header bg-info text-white">
                <h5><i class="fas fa-microphone"></i> Pronunciation</h5>
            </div>
            <div class="card-body">
                <div id="pronunciation-container">
                    <!-- Pronunciation items will be dynamically generated by JavaScript -->
                </div>
                
                <button type="button" class="btn btn-sm btn-primary" id="add-pronunciation-btn">
                    <i class="fas fa-plus"></i> Add Pronunciation
                </button>
            </div>
        </div>
        
        <div class="mt-4">
            <button id="show-data-btn" class="btn btn-info">Show Current Data</button>
            <pre id="data-display" class="mt-2 p-2 bg-light"></pre>
        </div>
    </div>
    
    <script>
        {open(js_file, 'r', encoding='utf-8').read()}
        
        // Initialize with test data
        document.addEventListener('DOMContentLoaded', function() {{
            console.log('DOM loaded, initializing component...');
            
            // Test with known pronunciation - Protestantism IPA
            const pronunciations = [
                {{
                    type: "seh-fonipa",
                    value: "ˈprɒtɪstəntɪzm",
                    audio_file: "",
                    is_default: true
                }}
            ];
            
            console.log('Initializing with pronunciations:', pronunciations);
            
            window.pronunciationFormsManager = new PronunciationFormsManager('pronunciation-container', {{
                pronunciations: pronunciations
            }});
            
            // Add button to show current data
            document.getElementById('show-data-btn').addEventListener('click', function() {{
                const container = document.getElementById('pronunciation-container');
                const items = container.querySelectorAll('.pronunciation-item');
                
                const data = [];
                items.forEach((item, index) => {{
                    const valueInput = item.querySelector('input[name$=".value"]');
                    const typeInput = item.querySelector('input[name$=".type"]');
                    const audioInput = item.querySelector('input[name$=".audio_file"]');
                    const defaultInput = item.querySelector('input[name$=".is_default"]');
                    
                    data.push({{
                        index,
                        value: valueInput ? valueInput.value : null,
                        type: typeInput ? typeInput.value : null,
                        audio_file: audioInput ? audioInput.value : null,
                        is_default: defaultInput ? defaultInput.checked : null
                    }});
                }});
                
                document.getElementById('data-display').textContent = JSON.stringify(data, null, 2);
            }});
        }});
    </script>
</body>
</html>
"""
    
    # Write to a file
    with open('pronunciation_test.html', 'w', encoding='utf-8') as f:
        f.write(html)
    
    print(f"Test page created: {os.path.abspath('pronunciation_test.html')}")
    print("Open this file in a web browser to test the pronunciation component.")
    print("\nTo test with the actual application, run:")
    print("python run.py")
    print("Then visit: http://127.0.0.1:5000/entries/Protestantism_b97495fb-d52f-4755-94bf-a7a762339605/edit")

if __name__ == '__main__':
    create_test_page()
