#!/usr/bin/env python3
"""
Create a test HTML file to debug the pronunciation forms.
"""

def create_test_html():
    """Create a simple test HTML file."""
    html = """<!DOCTYPE html>
<html>
<head>
    <title>Pronunciation Test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-4">
        <h1>Pronunciation Test</h1>
        
        <div id="pronunciation-container">
            <!-- Pronunciation items will be dynamically generated by JavaScript -->
        </div>
        
        <button type="button" class="btn btn-primary" id="add-pronunciation-btn">
            Add Pronunciation
        </button>
    </div>
    
    <script src="http://127.0.0.1:5000/static/js/pronunciation-forms.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            console.log('DOM loaded');
            console.log('PronunciationFormsManager:', window.PronunciationFormsManager);
            
            if (window.PronunciationFormsManager) {
                console.log('Creating PronunciationFormsManager');
                const pronunciations = [{
                    type: "seh-fonipa",
                    value: "ˈprɒtɪstənt",
                    audio_file: "",
                    is_default: true
                }];
                
                window.pronunciationFormsManager = new PronunciationFormsManager('pronunciation-container', {
                    pronunciations: pronunciations
                });
                console.log('PronunciationFormsManager created:', window.pronunciationFormsManager);
            } else {
                console.error('PronunciationFormsManager not found');
            }
        });
    </script>
</body>
</html>"""
    
    with open('d:\\Dokumenty\\slownik-wielki\\flask-app\\test_pronunciation.html', 'w', encoding='utf-8') as f:
        f.write(html)
    
    print("Test HTML created: test_pronunciation.html")
    print("Open in browser to test pronunciation forms")

if __name__ == '__main__':
    create_test_html()
